statements:
  - Effect: Allow
    Action:
      - dynamodb:PutItem
      - dynamodb:GetItem
      - dynamodb:Query
      - dynamodb:UpdateItem
    Resource:
      - !GetAtt MainTable.Arn
      # - !Join ['', [!GetAtt MainTable.Arn, '/index/*']]
      - !Sub '${MainTable.Arn}/index/*'
  - Effect: Allow
    Action: cognito-idp:AdminDeleteUser
    Resource: !GetAtt UserPool.Arn
